site_description: Vue.js — Прогрессивный JavaScript-фреймворк
google_analytics: UA-46852172-1
root_domain: ru.vuejs.org
vue_version: 2.7.14
# START SPONSORS
platinum:
  - name: Bit
    url: https://bit.dev
    img: bit.svg?v2
    priority: true
  - name: VueMastery
    url: https://www.vuemastery.com/
    img: vuemastery.png
  - name: VueSchool
    url: >-
      https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
  - name: Vehikl
    url: https://vehikl.com/
    img: vehikl.png
  - name: Passionate People
    url: https://passionatepeople.io/
    img: passionate_people.png
  - name: Storyblok
    url: https://www.storyblok.com
    img: storyblok.png
  - name: Chrome Frameworks Fund
    url: https://opencollective.com/2021-frameworks-fund
    img: chrome_frameworks_fund.png
  - name: HeroDevs
    url: https://www.herodevs.com/support/vue
    img: herodevs.png
  - name: JavaScript Certification
    url: https://certificates.dev/javascript/?ref=vuejs-sponsor&friend=VUEJS
    img: javascript_certification.png?v2
    description: Certification of competence for the JavaScript language
gold:
  - name: Tidelift
    url: https://tidelift.com/subscription/npm/vue
    img: tidelift.png
  - name: Laravel
    url: https://laravel.com/
    img: laravel.png
  - name: DevExpress
    url: https://js.devexpress.com/
    img: devexpress.png
  - name: LY Corporation
    url: https://www.lycorp.co.jp/en/
    img: ly_corporation.png?v2
  - name: Fenêtre Online Solutions
    url: https://www.fenetre.nl/
    img: fen_tre_online_solutions.svg
  - name: Ant Design Vue
    url: https://antdv.com
    img: ant_design_vue.png
  - name: Crisp
    url: https://crisp.chat/en/
    img: crisp.png
  - name: Localazy
    url: >-
      https://localazy.com/blog/how-to-localize-vuejs-app-with-vue-i18n-and-localazy?utm_source=vuejs&utm_medium=banner&utm_campaign=sponsorships_vuejs&utm_content=logo
    img: localazy.svg
  - name: uudetkasinot.com
    url: https://www.uudetkasinot.com
    img: uudetkasinot_com.png
  - name: Fathom Analytics
    url: https://usefathom.com/
    img: fathom_analytics.svg
  - name: Sentry
    url: https://sentry.io/for/vue?utm_source=vuejs.org&utm_medium=paid-community
    img: sentry.png
  - name: Famoid
    url: https://famoid.com/
    img: famoid.png
  - name: Certible
    url: https://www.certible.com
    img: certible.svg
  - name: FORTUNE GAMES
    url: https://www.fortunegames.com
    img: fortune_games.png
  - name: TBDC - Agro Software
    url: http://tbdc.com.br/
    img: tbdc___agro_software.svg
  - name: Quickbooks Tool Hub
    url: https://qbtoolhub.com/
    img: quickbooks_tool_hub.png
  - name: it@M
    url: ' https://opensource.muenchen.de/software/vue.js.html'
    img: it_m.png
  - name: Blastup
    url: https://blastup.com/buy-instagram-likes
    img: blastup.png
  - name: VueJobs
    url: https://vuejobs.com/?utm_source=vuejs.com&utm_campaign=sponsor
    img: vuejobs.png
  - name: Huly
    url: https://huly.io
    img: huly.svg
  - name: Automatenspieler
    url: https://automatenspieler.net/
    img: automatenspieler.png?v2
  - name: Stormlikes
    url: https://stormlikes.com
    img: stormlikes.png
  - name: Superviral
    url: https://superviral.io/
    img: superviral.png
  - name: Goread.io
    url: https://goread.io/buy-instagram-followers
    img: goread_io.png
  - name: Skweezer.net
    url: https://skweezer.net/
    img: skweezer_net.png
  - name: casinorevisor.com
    url: https://casinorevisor.com/
    img: casinorevisor_com.png
  - name: Famety - Buy Instagram Followers
    url: https://www.famety.com/
    img: famety___buy_instagram_followers.png
  - name: LambdaTest
    url: https://lambdatest.com/
    img: lambdatest.svg
  - name: Jspreadsheet
    url: https://jspreadsheet.com/
    img: jspreadsheet.png
  - name: Buy Youtube Subscribers
    url: https://ssmarket.net/buy-youtube-subscribers
    img: buy_youtube_subscribers.png
  - name: Leofame
    url: https://leofame.com/buy-instagram-followers
    img: leofame.png
  - name: SocialBoosting.com
    url: https://www.socialboosting.com/buy-tiktok-followers
    img: socialboosting_com.png
  - name: Poprey - Buy Instagram Likes
    url: https://poprey.com/
    img: poprey___buy_instagram_likes.png
silver:
  - name: Doximity
    url: https://technology.doximity.com/
    img: doximity.png
  - name: Codesmith
    url: https://codesmith.io
    img: codesmith.png
  - name: Optimizers
    url: https://www.optimizers.nl
    img: optimizers.png
  - name: FORTUNE GAMES
    url: https://www.fortunegames.com
    img: fortune_games.png
  - name: Indy
    url: https://www.indy.fr/
    img: indy.png
  - name: Buy Instagram Followers from SocialWick
    url: https://www.socialwick.com/instagram/followers
    img: buy_instagram_followers_from_socialwick.png
  - name: Social Followers
    url: https://www.socialfollowers.uk/buy-tiktok-followers/
    img: social_followers.png
  - name: Route Planner and Route Optimizer - Route4Me
    url: https://route4me.com
    img: route_planner_and_route_optimizer___route4me.png
  - name: Buy Instagram Followers Media Mister
    url: https://www.mediamister.com/buy-instagram-followers
    img: buy_instagram_followers_media_mister.png
  - name: https://nongamstopcasinos.net/en/
    url: https://nongamstopcasinos.net/en/
    img: https___nongamstopcasinos_net_en_.png
  - name: Playfortuneforfun.com
    url: https://playfortuneforfun.com/
    img: playfortuneforfun_com.png
  - name: Gamblechief.com
    url: https://gamblechief.com/
    img: gamblechief_com.png
  - name: Betwinner Partner
    url: https://betwinnerpartner.com/
    img: betwinner_partner.png
bronze:
  - name: Derek Pollard
    url: https://polyglotengineer.com/derek.pollard
    img: derek_pollard.png
  - name: BGASoft
    url: https://www.bgasoft.com
    img: bgasoft.png
  - name: RStudio
    url: https://rstudio.com
    img: rstudio.png
  - name: vuejs.de - German Vue Community
    url: https://vuejs.de
    img: vuejs_de___german_vue_community.svg
  - name: Liip AG
    url: https://www.liip.ch/en
    img: liip_ag.png
  - name: codefortynine
    url: https://codefortynine.com
    img: codefortynine.png
  - name: Routr
    url: http://www.routr.com
    img: routr.png
platinum_china:
  - name: CRMEB
    url: http://github.crmeb.net/u/vue
    img: crmeb.svg?v2
    description: 开源电商系统
# END SPONSORS
redirects:
  '/v2/api/index.html': '/api/'
  '/v2/guide/index.html': '/guide/introduction.html'
  '/v2/guide/installation.html': '/guide/quick-start.html'
  '/v2/guide/instance.html': '/guide/essentials/application.html' # has page redirects
  '/v2/guide/syntax.html': '/guide/essentials/template-syntax.html'
  '/v2/guide/computed.html': '/guide/essentials/computed.html' # has page redirects
  '/v2/guide/class-and-style.html': '/guide/essentials/class-and-style.html'
  '/v2/guide/conditional.html': '/guide/essentials/conditional.html'
  '/v2/guide/list.html': '/guide/essentials/list.html'
  '/v2/guide/events.html': '/guide/essentials/event-handling.html'
  '/v2/guide/forms.html': '/guide/essentials/forms.html'
  '/v2/guide/components.html': '/guide/essentials/component-basics.html'
  '/v2/guide/components-registration.html': '/guide/components/registration.html'
  '/v2/guide/components-props.html': '/guide/components/props.html' # has page redirects
  '/v2/guide/components-custom-events.html': '/guide/components/events.html'
  '/v2/guide/components-slots.html': '/guide/components/slots.html'
  '/v2/guide/components-dynamic-async.html': '/guide/built-ins/keep-alive.html' # has page redirects
  '/v2/guide/transitions.html': '/guide/built-ins/transition.html' # has page redirects
  '/v2/guide/transitioning-state.html': '/guide/extras/animation.html'
  '/v2/guide/custom-directive.html': '/guide/reusability/custom-directives.html'
  '/v2/guide/render-function.html': '/guide/extras/render-function.html'
  '/v2/guide/plugins.html': '/guide/reusability/plugins.html'
  '/v2/guide/single-file-components.html': '/guide/scaling-up/sfc.html'
  '/v2/guide/testing.html': '/guide/scaling-up/testing.html'
  '/v2/guide/typescript.html': '/guide/typescript/overview.html'
  '/v2/guide/deployment.html': '/guide/best-practices/production-deployment.html'
  '/v2/guide/routing.html': '/guide/scaling-up/routing.html'
  '/v2/guide/state-management.html': '/guide/scaling-up/state-management.html'
  '/v2/guide/ssr.html': '/guide/scaling-up/ssr.html'
  '/v2/guide/security.html': '/guide/best-practices/security.html'
  '/v2/guide/reactivity.html': '/guide/extras/reactivity-in-depth.html'
